//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCCas
    {
        public System.Guid KCCaseID { get; set; }
        public System.Guid KCPersonID { get; set; }
        public string CaseNumber { get; set; }
        public string Caption { get; set; }
        public string CaseNotes { get; set; }
        public string AllocationMethod { get; set; }
        public Nullable<double> Allocation { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
        public string CountyID { get; set; }
        public Nullable<int> DebtID { get; set; }
        public string DebtType { get; set; }
        public string CPName { get; set; }
        public string ThirdPartyPayeeName { get; set; }
        public Nullable<System.DateTime> DebtCreatedDate { get; set; }
        public string CaseStatus { get; set; }
        public bool MisappliedPaymentFlag { get; set; }
        public bool IsPayor { get; set; }
        public string AltCaseNumber { get; set; }
        public string OtherID { get; set; }
        public Nullable<bool> ToBeDeleted { get; set; }
    
        public virtual KCPerson KCPerson { get; set; }
    }
}
