//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCOrganization
    {
        public System.Guid KCOrganizationID { get; set; }
        public int KCOrgTypeID { get; set; }
        public string StateID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string FTIN { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
        public string Fax { get; set; }
        public Nullable<int> LastGlobalBatchID { get; set; }
        public Nullable<int> LastTransactionID { get; set; }
        public string Notes { get; set; }
        public int KCOrgPaymentMethodID { get; set; }
        public string ACHFileID { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastWebPayment { get; set; }
        public bool IsSDU { get; set; }
    }
}
