//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KCPerson()
        {
            this.KCCases = new HashSet<KCCas>();
            this.KCPersonAlias = new HashSet<KCPersonAlias>();
            this.KCPersonFinancials = new HashSet<KCPersonFinancial>();
            this.KCTrackDemographicChanges = new HashSet<KCTrackDemographicChanx>();
        }
    
        public System.Guid KCPersonID { get; set; }
        public string SSN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string WorkExtension { get; set; }
        public string eMail { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> PINNumber { get; set; }
        public string PersonID { get; set; }
        public string Pager { get; set; }
        public string AlternateEmail { get; set; }
        public string BillingEmail { get; set; }
        public byte KCDeliveryMethodID { get; set; }
        public bool FVI { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public bool InvalidAddress { get; set; }
        public bool DenyWebAccess { get; set; }
        public Nullable<byte> ChangeReasonCode { get; set; }
        public bool PaymentNotification { get; set; }
        public Nullable<System.DateTime> CreationStamp { get; set; }
        public Nullable<byte> KCPaymentMethodID { get; set; }
        public Nullable<System.DateTime> AddressStamp { get; set; }
        public Nullable<System.DateTime> PhoneStamp { get; set; }
        public Nullable<System.DateTime> EmailStamp { get; set; }
        public Nullable<System.DateTime> BillingEmailStamp { get; set; }
        public Nullable<System.DateTime> DeliveryMethodStamp { get; set; }
        public Nullable<System.DateTime> DODStamp { get; set; }
        public Nullable<System.DateTime> PaymentMethodStamp { get; set; }
        public Nullable<byte> SignMeUpForEbs { get; set; }
        public Nullable<bool> IVDStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCCas> KCCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCPersonAlias> KCPersonAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCPersonFinancial> KCPersonFinancials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KCTrackDemographicChanx> KCTrackDemographicChanges { get; set; }
    }
}
