//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCPersonAlias
    {
        public System.Guid KCPersonAliasID { get; set; }
        public System.Guid KCPersonID { get; set; }
        public string SSN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
        public string PersonID { get; set; }
    
        public virtual KCPerson KCPerson { get; set; }
    }
}
