//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Collections.Generic;
    
    public partial class KCTrackDemographicChanx
    {
        public int KCTrackDemographicChangesID { get; set; }
        public System.Guid KCPersonID { get; set; }
        public string Account { get; set; }
        public int RecordType { get; set; }
        public string FieldName { get; set; }
        public string FieldData { get; set; }
        public bool Exported { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
        public Nullable<System.DateTime> ModifiedStamp { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual KCPerson KCPerson { get; set; }
    }
}
