//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonLoad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonDBContext : DbContext
    {
        public PersonDBContext()
            : base("name=PersonDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KCCas> KCCases { get; set; }
        public virtual DbSet<KCOrganization> KCOrganizations { get; set; }
        public virtual DbSet<KCPerson> KCPersons { get; set; }
        public virtual DbSet<KCPersonAlias> KCPersonAliases { get; set; }
        public virtual DbSet<KCPersonFinancial> KCPersonFinancials { get; set; }
        public virtual DbSet<KCTrackDemographicChanx> KCTrackDemographicChanges { get; set; }
    }
}
